name: 'New deployment tool'
description: 'Deploy your project with ease'

inputs:
  github_token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Install Deno runtime to run the CLI
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run deployment tool 
      # Deno's runtime permissions are a great feature. It would be nice to take advantage of it, however, it may not be possible with future features like running plugins. 
      run: deno run --allow-env=GITHUB_REF,DRY_RUN,GITHUB_REPOSITORY,INPUT_GITHUB_TOKEN --allow-net="api.github.com" deploy.ts
      shell: bash 