name: 'New deployment tool'
description: 'Deploy your project with ease'

inputs:
  github_token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  version:
    description: 'Version of the CLI to use.'
    default: 'main' # using branch name for now for easier deployments 
  deploy_commands:
    description: 'List of commands to run to deploy your project.'
    required: true
    default: '[]'

runs:
  using: "composite"
  steps:
    - name: Install Deno runtime to run the CLI
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run deployment tool 
      # Deno's runtime permissions are a great feature. It would be nice to take advantage of it, however, it may not be possible with future features like running plugins. 
      run: deno run --allow-env=GITHUB_REF,DRY_RUN,GITHUB_REPOSITORY,INPUT_GITHUB_TOKEN,INPUT_DEPLOY_COMMANDS,TMPDIR --allow-net="api.github.com" --allow-run --allow-write="$TMPDIR" https://raw.githubusercontent.com/levibostian/new-deployment-tool/${{ inputs.version }}/deploy.ts
      shell: bash 
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_DEPLOY_COMMANDS: ${{ inputs.deploy_commands }}