version: 2.1
orbs:
  gh: circleci/github-cli@3.0.0
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.11.1
    steps:
      - checkout
      - gh/install
      
      - run: 
          name: Install langs/tools 
          command: |
            curl https://mise.run | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$BASH_ENV"
            echo 'eval "$(/home/circleci/.local/bin/mise activate bash)"' >> "$BASH_ENV"
            source "$BASH_ENV"
            mise install

      # Install a specific version of the tool (recommended for teams)
      # - run: curl -fsSL https://github.com/levibostian/decaf/blob/HEAD/install?raw=true | bash "1.0.0"
      # --- 
      # To always install the latest version (not recommended for teams):
      # - run: curl -fsSL https://github.com/levibostian/decaf/blob/HEAD/install?raw=true | bash

      # Compile and run so we can test the recent code changes in project. 
      # This is used for development purposes only.
      - run: 
          name: Compile binary
          command: OUTPUT_FILE_NAME=decaf DENO_TARGET="$(uname -m)-unknown-linux-gnu" deno task compile

      - run:
          name: Run CLI Tool
          # The auth token given to decaf is read-only so we need to disable some features. 
          command: |
            ./decaf \
              --github_token "$GH_TOKEN" \
              --deploy "OUTPUT_FILE_NAME=dist/bin-x86_64-Linux DENO_TARGET=x86_64-unknown-linux-gnu deno task compile && \
                OUTPUT_FILE_NAME=dist/bin-aarch64-Linux DENO_TARGET=aarch64-unknown-linux-gnu deno task compile && \
                OUTPUT_FILE_NAME=dist/bin-x86_64-Darwin DENO_TARGET=x86_64-apple-darwin deno task compile && \
                OUTPUT_FILE_NAME=dist/bin-aarch64-Darwin DENO_TARGET=aarch64-apple-darwin deno task compile && \
                deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-git.git/shebang.sh@shebang merge-into-release-branch --release-branch latest && \
                deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-git.git/shebang.sh@shebang commit-and-push --add version.txt && \
                deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@shebang set-github-release-assets dist/bin-x86_64-Linux#x86_64-unknown-linux-gnu dist/bin-aarch64-Linux#aarch64-unknown-linux-gnu dist/bin-x86_64-Darwin#x86_64-apple-darwin dist/bin-aarch64-Darwin#aarch64-apple-darwin && \
                deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@shebang set --release-branch latest" \
              --get_latest_release_current_branch "deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@shebang get --release-branch latest" \
              --get_next_release_version "deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits" \
              --make_pull_request_comment false \
              --output_file "/tmp/decaf-output.json" \
              --debug true 

      - run: 
          name: Show Output File
          command: cat /tmp/decaf-output.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - main
                - latest