name: Deploy

on: 
  push:
    branches: [main, alpha, beta]
  # This tool encourages you to run it on pull requests to test the deployment process.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:    
      contents: write # required to create git tags and releases
      pull-requests: write # allow commenting on PRs
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    
    - name: Run decaf to perform deployment
      uses: ./
      env:
        # required to use 'gh' CLI in my step scripts. 
        GH_TOKEN: ${{ github.token }}
      with: 
        compile_binary: 'true'
        github_token: ${{ secrets.github_token }}
        get_latest_release_current_branch: decaf shebang https://github.com/levibostian/decaf-script-github-releases.git/shebang.sh@install-mise get
        get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
        deploy: './deploy.ts'