name: Deploy

on: 
  push:
    branches: [main, alpha, beta]
  # This tool encourages you to run it on pull requests to test the deployment process.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:    
      contents: write # required to create git tags and releases
      pull-requests: write # allow commenting on PRs
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    
    - name: Run decaf to perform deployment
      uses: ./
      env:
        # required to use 'gh' CLI in my step scripts. 
        GH_TOKEN: ${{ github.token }}
      with: 
        compile_binary: 'true'
        github_token: ${{ secrets.github_token }}
        get_latest_release_current_branch: deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@shebang get --release-branch latest
        get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
        deploy: |
          OUTPUT_FILE_NAME=dist/bin-x86_64-Linux DENO_TARGET=x86_64-unknown-linux-gnu deno task compile
          OUTPUT_FILE_NAME=dist/bin-aarch64-Linux DENO_TARGET=aarch64-unknown-linux-gnu deno task compile
          OUTPUT_FILE_NAME=dist/bin-x86_64-Darwin DENO_TARGET=x86_64-apple-darwin deno task compile
          OUTPUT_FILE_NAME=dist/bin-aarch64-Darwin DENO_TARGET=aarch64-apple-darwin deno task compile 
          deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-git.git/shebang.sh@shebang merge-into-release-branch --release-branch latest
          deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-git.git/shebang.sh@shebang commit-and-push --add version.txt 
          deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@shebang set-github-release-assets dist/bin-x86_64-Linux#x86_64-unknown-linux-gnu dist/bin-aarch64-Linux#aarch64-unknown-linux-gnu dist/bin-x86_64-Darwin#x86_64-apple-darwin dist/bin-aarch64-Darwin#aarch64-apple-darwin
          deno run --allow-all --quiet index.ts shebang https://github.com/levibostian/decaf-script-github-releases-release-branch.git/shebang.sh@shebang set --release-branch latest