on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Deno
      uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4

    - name: Run formatter and fail if not formatted
      run: |
        deno fmt --check || (echo "Code has not been formatted. May I suggest you install git hooks on your development machine?" && exit 1)

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Deno
      uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4

    - name: Run lint and fail if there are errors
      run: |
        deno lint || (echo "Lint errors found. Please fix the issues above." && exit 1)